export const AGREGAR_JUGADOR = "AGREGAR_JUGADOR";
export const AGREGAR_JUGADOR_EXITO = "AGREGAR_JUGADOR_EXITO";
export const AGREGAR_JUGADOR_ERROR = "AGREGAR_JUGADOR_ERROR";

// JUGADORES
export const COMENZAR_DESCARGA_JUGADORES = "COMENZAR_DESCARGA_JUGADORES";
export const DESCARGA_JUGADORES_EXITO = "DESCARGA_JUGADORES_EXITO";
export const DESCARGA_JUGADORES_ERROR = "DESCARGA_JUGADORES_ERROR";
